name: 'Setup Dependencies'
description: 'Install platform-specific dependencies for building CLAP plugin'
inputs:
  platform:
    description: 'Platform to setup (linux, windows, macos)'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Install dependencies (Linux)
    if: inputs.platform == 'linux'
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install -y build-essential cmake git python3 python3-pip
      sudo apt-get install -y pkg-config
      # Install Rust for clap-validator
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
  - name: Install dependencies (Windows)
    if: inputs.platform == 'windows'
    shell: pwsh
    run: |
      # Install Chocolatey if not present
      if (!(Get-Command choco -ErrorAction SilentlyContinue)) {
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      }
      # Install required tools
      choco install -y git cmake visualstudio2022buildtools rust
      # Ensure tools are in PATH
      refreshenv
      
  - name: Install dependencies (macOS)
    if: inputs.platform == 'macos'
    shell: bash
    run: |
      # Install Xcode command line tools if not present
      xcode-select --install || true
      # Install Rust for clap-validator
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      echo "$HOME/.cargo/bin" >> $GITHUB_PATH
